apiVersion: v1
kind: ConfigMap
metadata:
  name: kapparmor-settings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kapparmor.labels" . | nindent 4 }}
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  PROFILES_DIR: "{{ .Values.app.profiles_dir }}"
  POLL_TIME: "{{ .Values.app.poll_time }}"