apiVersion: v1
kind: ConfigMap
metadata:
  name: kapparmor-settings
  namespace: {{ .Release.Namespace }}
data:
  PROFILES_DIR: "{{ .Values.app.profiles_dir }}"
  POLL_TIME: "{{ .Values.app.poll_time }}"