apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kapparmor.fullname" . }}
  labels:
    {{- include "kapparmor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kapparmor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kapparmor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kapparmor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # mount a configmap as read only in the container's filesystem.  
          volumeMounts :
            - name : kapparmor-profiles
              mountPath : {{ .Values.app.profiles_dir }}
              readOnly : false
            - name: profiles-kernel-path
              mountPath: /sys/kernel/security
            - name: etc-apparmor
              mountPath: /etc/apparmor.d/

          env:
            - name: PROFILES_DIR
              valueFrom:
                configMapKeyRef:
                  name: kapparmor-settings
                  key: PROFILES_DIR
            - name: POLL_TIME
              valueFrom:
                configMapKeyRef:
                  name: kapparmor-settings
                  key: POLL_TIME

      volumes:
        - name: kapparmor-profiles
          configMap:
            name: kapparmor-profiles
        - name: profiles-kernel-path
          hostPath:
            path: /sys/kernel/security
        - name: etc-apparmor
          hostPath:
            path: /etc/apparmor.d/

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
