coverage:
  # Display coverage percentage with 1 decimal point (XX.X%).
  precision: 1
  round: down
  # The value range where you want the value to be green
  range: "50..100"
  status:
    project:
      default:
        # Do not use coverage drop as a reason to mark the CI check red
        threshold: "100%"
    # Do not fail Github checks for patches with low coverage: treat them as informational.
    # https://docs.codecov.com/docs/common-recipe-list#set-non-blocking-status-checks
    patch:
      default:
        informational: true

fixes:
  - "github.com/tuxerrante/kapparmor/::github.com/tuxerrante/kapparmor/go/src/app/" 

# Disable codecov annotations in Github files changed tab in PRs.
# https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml
github_checks:
  annotations: false