name: "1. Create app"

on:
  push:
    branches: [main]
    paths:
      - "go/src/app/**.go"
      - Dockerfile
      - ".github/workflows/*"
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  GO_VERSION: '1.19'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go get -d -v ./go/src/app/
      - name: Build
        run: go build -v -o ./go/bin/app ./go/src/app/
      # - name: Test with the Go CLI
      #   run: go test

      - name: 'Tar files'
        run: tar -czvf app.tar.gz ./go/bin/app

      - name: Archive go artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'app.tar.gz'
          path: 'app.tar.gz'
  build-and-push-image:
    needs: 'build-app'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download go bin artifact
        uses: actions/download-artifact@v3
        with:
          name: 'app.tar.gz'
      
      - name: 'UnTar files'
        run: tar -xvf app.tar.gz -C go/bin/

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "--progress=plain"